use super::Page;

pub(crate) const NORMAL: [Page; 9] = [
    Page {
        title: "G-Force Coaster",
        description: "It's a looping rollercoaster of some description. They want to install it in a prison, not for any sort of un-needed fun. You're not smart enough to analyse the engineer's drawings, but you're sure they know what they're doing.",
        accept: true,
        bonus: 100,
        penalty: 100,
    },
    Page {
        title: "New Regime Propaganda",
        description: r#""War is Peace. Freedom is Slavery. Ignorance is Strength," the poster reads. It has the eyes of The Best President on it, credited to a certain G. Orwell. You've seen this before, perhaps it just came back through."#,
        accept: true,
        bonus: 10,
        penalty: 200,
    },
    Page {
        title: "Raindrop Man and a Purple Monster",
        description: "Attributed to a T. Fox. Sounds like a reasonable fellow, you've seen some of his works in the Approved Fun Time section of GreatMart.",
        accept: true,
        bonus: 100,
        penalty: 100,
    },
    Page {
        title: "Family Barbecue",
        description: "All approved Genomonicalundically Great Again Meat and Vegetables, on a GreatMart Grill. All social standings are in order, and The Best President is invited. Not sure he will arrive, but that means it fits the criteria.",
        accept: true,
        bonus: 20,
        penalty: 10,
    },
    Page {
        title: "GreatMart Electrofunksical Vehiculating Passengercraft",
        description: "Thank BestGreatEducation you can read words sufficiently long enough for the right people to understand, and the wrong people to not. It's by GreatMart, the Best Approved Superdunglemarketplace in all of the 190 States.",
        accept: true,
        bonus: 90,
        penalty: 150,
    },
    Page {
        title: "Fun Coloured Banner",
        description: "Made by a paid worker? Is this some sort of joke?",
        accept: false,
        bonus: 160,
        penalty: 200,
    },
    Page {
        title: "Sparlock kids' action toy",
        description: "Some sort of warrior wizard. I don't think the organisation approves of this.",
        accept: false,
        bonus: 10,
        penalty: 200,
    },
    Page {
        title: "Unauthorised Flatulence",
        description: "Gross.",
        accept: false,
        bonus: 50,
        penalty: 50,
    },
    Page {
        title: "Dissenting Poster",
        description: r#""We live in an authoritarian society! We are being subject to censorship! Rise up now." What a load of rubbish."#,
        accept: false,
        bonus: 200,
        penalty: 250,
    },
];

pub(crate) const TIRED: [Page; 10] = [
    Page {
        title: "An Eye.",
        description: "I don't see why not.",
        accept: true,
        bonus: 124,
        penalty: 245,
    },
    Page {
        title: "Normal Pills",
        description: "GreatHealth is grrreat! You take one every morning. New recipe?",
        accept: true,
        bonus: 53,
        penalty: 98,
    },
    Page {
        title: "Hand with Six Fingers",
        description: "Submitted by a man named Humperdink. You shiver at the sound of that word, but you are pretty sure this is the King of Mainappendage's hand and they've never hurt you.",
        accept: true,
        bonus: 157,
        penalty: 231,
    },
    Page {
        title: "A Piece of Paper on the Piece of Paper",
        description: "GreatGovernnent wishes to Intellectually Acquire this Property for the Greater Good of Printermachinationcraft.",
        accept: true,
        bonus: 142,
        penalty: 236,
    },
    Page {
        title: "8 Day Work Week",
        description: "Official decree by the GreatSuperCongress. They know what's best.",
        accept: true,
        bonus: 26,
        penalty: 196,
    },
    Page {
        title: "Prisoner's Cry for Help",
        description: "Some letter from an inmate. I thought they were banned from using pens and paper?",
        accept: false,
        bonus: 152,
        penalty: 253,
    },
    Page {
        title: "An Eye?",
        description: "I will see to this being destroyed.",
        accept: false,
        bonus: 25,
        penalty: 203,
    },
    Page {
        title: "Unapproved Whimsical Illustration",
        description: "Who gave this child crayons? This is directly against the policy of The Nation.",
        accept: false,
        bonus: 106,
        penalty: 209,
    },
    Page {
        title: "Game Rated for Old Teens",
        description: "Isn't there a payment processor we should consult about this? I don't think they would approve.",
        accept: false,
        bonus: 213,
        penalty: 143,
    },
    Page {
        title: "Journalist",
        description: "Who is this guy? Wants a permit to view the Great Food Distribution Service. He has a camera too, we need to get that removed.",
        accept: false,
        bonus: 2,
        penalty: 254,
    },
];

pub(crate) const INSANE: [Page; 10] = [
    Page {
        title: "???",
        description: "You aren't quite sure.",
        accept: true,
        bonus: 0,
        penalty: 255,
    },
    Page {
        title: "Skulls",
        description: "I AM WATCHING YOU.",
        accept: true,
        bonus: 0,
        penalty: 255,
    },
    Page {
        title: "NOBODY WILL HEAR YOU.",
        description: "GO ON. SCREAM. Fool.",
        accept: true,
        bonus: 0,
        penalty: 255,
    },
    Page {
        title: "QUIT YOUR JOB.",
        description: "Join Proper Manly Man University.",
        accept: true,
        bonus: 0,
        penalty: 255,
    },
    Page {
        title: "|:||:|I:|_",
        description: "Some cruel inside joke.",
        accept: true,
        bonus: 0,
        penalty: 255,
    },
    Page {
        title: "GO AWAY.",
        description: "NOW.",
        accept: false,
        bonus: 0,
        penalty: 255,
    },
    Page {
        title: "A Sobbing Mother",
        description: "Look what you did to her!",
        accept: false,
        bonus: 0,
        penalty: 255,
    },
    Page {
        title: "PRESS RELEASE OF SKULLS",
        description: "This may infringe on The Leader's privacy.",
        accept: false,
        bonus: 0,
        penalty: 255,
    },
    Page {
        title: "HAHAHAHAHAHAHAHAHAHAHAHAHA",
        description: "HAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHA",
        accept: false,
        bonus: 0,
        penalty: 255,
    },
    Page {
        title: "I TOLD YOU SO.",
        description: "I TOLD YOU SO.",
        accept: false,
        bonus: 0,
        penalty: 255,
    },
];
