web:
	# multithreaded
	RUSTFLAGS="-C link-args=-pthread -C target-feature=+atomics -C link-args=-sSIDE_MODULE=2 -Zlink-native-libraries=no -Cllvm-args=-enable-emscripten-cxx-exceptions=0" cargo +nightly build -Zbuild-std --target wasm32-unknown-emscripten
	mv target/wasm32-unknown-emscripten/debug/fpwe.wasm target/wasm32-unknown-emscripten/debug/fpwe.threads.wasm
	# singlethreaded
	cargo +nightly build --features nothreads -Zbuild-std --target wasm32-unknown-emscripten
