[toolchain]
channel = "nightly"
components = ["rust-src"]
targets = [
	"x86_64-unknown-linux-gnu", # linux (x86_64)
	"x86_64-pc-windows-msvc", # windows (x86_64)
	"x86_64-apple-darwin", # macOS (x86_64)
	"aarch64-apple-darwin", # macOS (arm64)
	"wasm32-unknown-emscripten" # web (wasm)
]
